### ISSUE TITLE
Imported Dashboards are Blank

### ISSUE THREAD

**Issue by ChosunOne** [glamperd/lh-validator-metrics#1]
System: Ubuntu 20.04 LXC Container

I've setup pushgateway and set Prometheus to scrape it (see prometheus screenshot below):
![image](https://user-images.githubusercontent.com/5751289/90852006-f323b280-e33b-11ea-9385-e01aaba316e7.png)

I've also confirmed that my cron job is executing as my syslog reports:
```
Aug 21 04:00:01 lighthouse-metrics CRON[3624]: (chosunone) CMD (bash /home/chosunone/lh-validator-metrics/push_metrics.sh >>/dev/null 2>&1 | logger -t pushmetrics)
Aug 21 04:05:01 lighthouse-metrics CRON[3766]: (chosunone) CMD (bash /home/chosunone/lh-validator-metrics/push_metrics.sh >>/dev/null 2>&1 | logger -t pushmetrics)
Aug 21 04:10:01 lighthouse-metrics CRON[3818]: (chosunone) CMD (bash /home/chosunone/lh-validator-metrics/push_metrics.sh >>/dev/null 2>&1 | logger -t pushmetrics)
Aug 21 04:15:01 lighthouse-metrics CRON[4057]: (chosunone) CMD (bash /home/chosunone/lh-validator-metrics/push_metrics.sh >>/dev/null 2>&1 | logger -t pushmetrics)
Aug 21 04:20:01 lighthouse-metrics CRON[4119]: (chosunone) CMD (bash /home/chosunone/lh-validator-metrics/push_metrics.sh >>/dev/null 2>&1 | logger -t pushmetrics)
```

But when I import the json dashboards into grafana I am met with a blank dashboard:
![image](https://user-images.githubusercontent.com/5751289/90852135-501f6880-e33c-11ea-9ea1-f35349833426.png)

**Comment by ChosunOne** [comment]
Workaround by changing line 6 of the push_metrics.sh script to use `${vals1}` instead of `${vals}`.  The dashboards are still blank but I can create my own panels with data.

**Comment by glamperd** [comment]
I've revised the push_metrics.sh script to parse the validator list differently. That should solve this problem. The dashboard should catch up after a few minutes of good data.
